# Lista de plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# Configuraciones de persistencia automatizada
set -g @continuum-restore 'on'
set -g @resurrect-capture-pane-contents 'on'

# Inicializar TPM (Mantén esta línea siempre al final del archivo)
run '~/.tmux/plugins/tpm/tpm'

set -g mouse on
