# ===========================================
# Configuración de Plugins (PPM)
# ===========================================
set -g @plugin 'psmux-plugins/ppm'
set -g @plugin 'psmux-plugins/psmux-resurrect'

# Inicializar PPM (dejar esta línea al fondo del archivo)
# run '~/.psmux/plugins/ppm/ppm.ps1'

# Activar el soporte nativo de mouse
set -g mouse on

# Permitir que la rueda central entre automáticamente al modo copia al hacer scroll
set -g scroll-enter-copy-mode on

# Selección de texto optimizada al soltar el clic para PowerShell
set -g pwsh-mouse-selection on